nodeLinker: node-modules

packageExtensions:
  "@redocly/cli@*":
    dependencies:
      lodash.isequal: "*"
      node-fetch: ^2
      react-is: "*"
  redoc@*:
    dependencies:
      call-me-maybe: "*"
      fast-safe-stringify: "*"
      yaml: "*"
