// Renders the v3 GraphQL API reference as Mintlify MDX from the doc model.
//
// Input is redo/api-schema-v3/v3.docs.json — a doc model emitted by the v3
// server's Pothos schema walk. It carries categories, per-op and per-field
// scopes, lifecycle, webhook topics, and pre-resolved type display strings, so
// this script is a pure renderer: no GraphQL parsing.
//
// Layout: one page PER ENTITY, grouped by category —
//   reference/<category>/overview.mdx        (category landing + index)
//   reference/<category>/queries/<op>.mdx    (one per query)
//   reference/<category>/mutations/<op>.mdx  (one per mutation)
//   reference/<category>/<Type>.mdx          (one per named type)
//   reference/scopes.mdx                      (the access-scope catalog)
//
// Pagination boilerplate (`*Connection` / `*Edge` / `PageInfo`) is collapsed —
// documented once on the Pagination guide, and paginated fields link there.
//
// The generator also PATCHES docs.json's v3 nav (category groups with
// Queries/Mutations subgroups and one entry per type), preserving the
// hand-authored "Getting Started" group.
//
// Usage:
//   node generate.js --model <v3.docs.json> --out <dir> [--docs-json <docs.json>]
//
// Exits non-zero (failing the Bazel build) if the model is internally
// inconsistent (dangling category, unknown scope, unresolved type).

const fs = require("fs");
const path = require("path");
const prettier = require("prettier");

const REFERENCE_BASE = "/docs/api-reference/v3/reference";
const PAGINATION_PAGE = "/docs/api-reference/v3/pagination";
const SCOPES_SLUG = "scopes";
const SCOPES_PAGE = `${REFERENCE_BASE}/${SCOPES_SLUG}`;
const BUILTIN_SCALARS = new Set(["String", "Int", "Float", "Boolean", "ID"]);

// How many levels of nested fields to expand inline in the operation field
// explorer. GraphQL types are cyclic and Mintlify pre-renders every Expandable
// into the page, so beyond this depth (or when a type recurses onto itself) a
// field stops expanding and just links to its own page.
const MAX_DEPTH = 3;

// Order types are listed within a category (nav + overview index).
const KIND_ORDER = [
  ["Objects", "OBJECT"],
  ["Interfaces", "INTERFACE"],
  ["Input objects", "INPUT_OBJECT"],
  ["Enums", "ENUM"],
  ["Scalars", "SCALAR"],
];

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 2) {
    args[argv[i].replace(/^--/, "")] = argv[i + 1];
  }
  return args;
}

function fail(messages) {
  console.error("\n  v3 GraphQL docs generation failed:\n");
  for (const m of messages) console.error(`    - ${m}`);
  console.error(
    "\n  The doc model (redo/api-schema-v3/v3.docs.json) is inconsistent. It is" +
      "\n  emitted by the v3 server; regenerate it there and re-vendor.\n"
  );
  process.exit(1);
}

function isBoilerplate(name) {
  return (
    name.endsWith("Connection") || name.endsWith("Edge") || name === "PageInfo"
  );
}

// Mutation payload wrappers (e.g. CreateWebhookEndpointResult). Documented on
// the mutation that returns them, so they get a page but no nav/index entry.
function isResultObject(type) {
  return type.kind === "OBJECT" && /(Result|Payload)$/.test(type.name);
}

// PascalCase / camelCase -> kebab-case, for page slugs.
function slug(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

// Escape MDX-special characters in model-authored prose. MDX reads `{` as an
// expression and `<` as JSX, so unescaped braces/angles are a parse error. We
// must NOT escape inside inline code spans (`` `...` ``), where MDX treats the
// content as literal — so split on code spans and only escape plain text.
function mdxText(text) {
  if (!text) return "";
  return text
    .split(/(`[^`]*`)/)
    .map((seg, i) =>
      i % 2 === 1 ? seg : seg.replace(/[{}<]/g, (c) => "\\" + c)
    )
    .join("");
}

function escapeCell(text) {
  return mdxText(text).replace(/\n+/g, " ").replace(/\|/g, "\\|").trim();
}

function oneLine(text) {
  return (text || "").replace(/\s+/g, " ").trim();
}

function frontmatter(title, description) {
  return [
    "---",
    `title: ${JSON.stringify(title)}`,
    `description: ${JSON.stringify(oneLine(description) || title)}`,
    "---",
    "",
    "{/* Generated by tools/graphql/generate.js from redo/api-schema-v3/v3.docs.json. Do not edit by hand — run `bazel run graphql_gen`. */}",
    "",
  ];
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const { model: modelPath, out: outDir, "docs-json": docsJsonPath } = args;
  if (!modelPath || !outDir) fail(["--model and --out are both required"]);

  const model = JSON.parse(fs.readFileSync(modelPath, "utf8"));
  let categories = [...(model.categories || [])].sort((a, b) =>
    a.label.localeCompare(b.label)
  );
  const types = model.types || [];
  const queries = model.queries || [];
  const mutations = model.mutations || [];
  const scopes = model.scopes || [];

  const typeByName = Object.fromEntries(types.map((t) => [t.name, t]));
  const categoryIds = new Set(categories.map((c) => c.id));
  const scopeIds = new Set(scopes.map((s) => s.scope));

  // ----- Validate referential integrity of the model -----
  const errors = [];
  const referencedScopes = new Set();

  function noteScopes(list) {
    for (const s of list || []) {
      referencedScopes.add(s);
      if (!scopeIds.has(s)) errors.push(`scope "${s}" is not in the catalog`);
    }
  }
  function checkTypeRef(ref, where) {
    if (!ref || !ref.ofType) return;
    const n = ref.ofType;
    if (!BUILTIN_SCALARS.has(n) && !typeByName[n]) {
      errors.push(`${where}: type "${n}" is not in the model`);
    }
  }
  function checkCategory(cat, where) {
    if (!categoryIds.has(cat))
      errors.push(`${where}: unknown category "${cat}"`);
  }

  for (const op of [...queries, ...mutations]) {
    checkCategory(op.category, `${op.kind} ${op.name}`);
    noteScopes(op.scopes);
    checkTypeRef(op.returnType, `${op.kind} ${op.name} return`);
    for (const a of op.args || [])
      checkTypeRef(a.type, `${op.kind} ${op.name} arg ${a.name}`);
  }
  for (const t of types) {
    if (t.category) checkCategory(t.category, `type ${t.name}`);
    noteScopes(t.scopes);
    for (const f of t.fields || []) {
      noteScopes(f.scopes);
      checkTypeRef(f.type, `${t.name}.${f.name}`);
      for (const a of f.args || [])
        checkTypeRef(a.type, `${t.name}.${f.name} arg ${a.name}`);
    }
    for (const f of t.inputFields || [])
      checkTypeRef(f.type, `${t.name}.${f.name} (input)`);
  }
  if (errors.length) fail(errors);

  // Categories can be declared in the model before they have any queries,
  // mutations, or types (the API grows ahead of its content). Skip those rather
  // than emitting an empty page/nav group — they appear once they have members.
  const populated = new Set([
    ...types.map((t) => t.category),
    ...queries.map((q) => q.category),
    ...mutations.map((m) => m.category),
  ]);
  const emptyCategories = categories
    .filter((c) => !populated.has(c.id))
    .map((c) => c.id);
  categories = categories.filter((c) => populated.has(c.id));

  // ----- URL / link helpers -----
  const overviewUrl = (catId) => `${REFERENCE_BASE}/${catId}/overview`;
  const opUrl = (op) =>
    `${REFERENCE_BASE}/${op.category}/${
      op.kind === "query" ? "queries" : "mutations"
    }/${slug(op.name)}`;
  function typeUrl(name) {
    const t = typeByName[name];
    return t ? `${REFERENCE_BASE}/${t.category}/${slug(name)}` : null;
  }

  function scopeList(list) {
    if (!list || list.length === 0) return "_None_";
    return list.map((s) => `[\`${s}\`](${SCOPES_PAGE}#scope-${s})`).join(", ");
  }

  function lifecycleBadge(lifecycle) {
    if (!lifecycle || lifecycle === "ga") return "";
    const label = lifecycle.charAt(0).toUpperCase() + lifecycle.slice(1);
    return ` **(${label})**`;
  }

  // ----- Example operations (built from the model) -----
  function firstEnumValue(typeName) {
    const t = typeByName[typeName];
    return t && t.values && t.values[0] ? t.values[0].name : '"..."';
  }
  function exampleArgValue(ref) {
    const n = ref.ofType;
    if (n === "ID" || n === "String") return '"..."';
    if (n === "Int") return "10";
    if (n === "Float") return "0.0";
    if (n === "Boolean") return "true";
    if (ref.kind === "ENUM") return firstEnumValue(n);
    if (ref.kind === "INPUT_OBJECT") return "{ ... }";
    return '"..."';
  }
  function selectionLines(typeName, indent, depth) {
    const t = typeByName[typeName];
    if (!t || depth <= 0 || !(t.fields && t.fields.length)) return [];
    const pad = "  ".repeat(indent);
    if (typeName.endsWith("Connection")) {
      const nodes = t.fields.find((f) => f.name === "nodes");
      const nodeType = nodes ? nodes.type.ofType : null;
      return [
        `${pad}nodes {`,
        ...selectionLines(nodeType, indent + 1, depth - 1),
        `${pad}}`,
        `${pad}pageInfo { hasNextPage endCursor }`,
      ];
    }
    const lines = [];
    let count = 0;
    for (const f of t.fields) {
      if (count >= 8) {
        lines.push(`${pad}# ...`);
        break;
      }
      if (f.type.kind === "SCALAR" || f.type.kind === "ENUM") {
        lines.push(`${pad}${f.name}`);
        count++;
      } else if (
        f.type.ofType &&
        f.type.ofType.endsWith("Connection") &&
        depth > 1
      ) {
        lines.push(`${pad}${f.name} {`);
        lines.push(...selectionLines(f.type.ofType, indent + 1, 2));
        lines.push(`${pad}}`);
        count++;
      }
    }
    return lines;
  }
  function exampleOperation(op) {
    const argList = (op.args || [])
      .map((a) => `${a.name}: ${exampleArgValue(a.type)}`)
      .join(", ");
    const head = argList ? `${op.name}(${argList})` : op.name;
    const selection = selectionLines(op.returnType.ofType, 2, 2);
    const body = selection.length ? ` {\n${selection.join("\n")}\n  }` : "";
    return ["```graphql", `${op.kind} {`, `  ${head}${body}`, "}", "```"].join(
      "\n"
    );
  }

  // ----- Enum values table (type pages) -----
  function enumTable(type) {
    let out = "\n| Value | Description |\n| --- | --- |\n";
    for (const v of type.values || [])
      out += `| \`${v.name}\`${lifecycleBadge(v.lifecycle)} | ${escapeCell(
        v.description
      )} |\n`;
    return out;
  }
  const implementorsOf = (ifaceName) =>
    types.filter((t) => (t.interfaces || []).includes(ifaceName));
  function webhooksLine(type) {
    if (!type.webhooks || type.webhooks.length === 0) return "";
    const topics = type.webhooks.map((w) => `\`${w}\``).join(", ");
    return `**[Emits](${overviewUrl("webhooks")}):** ${topics}`;
  }

  // ----- Inline field explorer (operation Arguments / Returns) -----
  // The fields to expand for a named type: object/interface fields, or an input
  // object's input fields. Null for scalars/enums (nothing to expand).
  function fieldsOf(type) {
    if (!type) return null;
    if (type.kind === "OBJECT" || type.kind === "INTERFACE")
      return type.fields || null;
    if (type.kind === "INPUT_OBJECT") return type.inputFields || null;
    return null;
  }

  // <ResponseField>'s `type` prop renders plain text, so to keep the type a
  // clickable link (like Shopify) we pass a JSX anchor as the prop value.
  // Connections link to the Pagination guide, named types to their page,
  // built-ins stay plain text.
  function typeAttr(ref) {
    const { display, ofType } = ref;
    let href = null;
    if (ofType && !BUILTIN_SCALARS.has(ofType))
      href = isBoilerplate(ofType) ? PAGINATION_PAGE : typeUrl(ofType);
    return href
      ? `type={<a href="${href}">${display}</a>}`
      : `type="${display}"`;
  }

  // Render one field as a <ResponseField> (name pill + linked type + required
  // badge + description). If the field takes arguments or its type has fields —
  // and we're within depth and not cycling — nest an <Expandable> with the
  // field's own **Arguments** and the type's **Fields**, each a ResponseField.
  function renderField(field, ancestors, depth, pad) {
    const required = field.type.display.endsWith("!") ? " required" : "";
    const out = [
      `${pad}<ResponseField name="${field.name}" ${typeAttr(
        field.type
      )}${required}>`,
    ];
    if (field.description)
      out.push("", `${pad}  ${mdxText(field.description)}`);
    if (field.scopes && field.scopes.length)
      out.push("", `${pad}  **Requires:** ${scopeList(field.scopes)}`);

    const args = field.args || [];
    const named = field.type.ofType;
    const typeFields =
      named && !BUILTIN_SCALARS.has(named) ? fieldsOf(typeByName[named]) : null;
    const showFields =
      typeFields &&
      typeFields.length &&
      depth < MAX_DEPTH &&
      !ancestors.has(named);

    if (args.length || showFields) {
      const inner = `${pad}    `;
      out.push("", `${pad}  <Expandable title="fields" lazyRender>`, "");
      if (args.length) {
        out.push(`${inner}**Arguments**`, "");
        // Arguments live in the current context, not inside the field's type.
        for (const a of args)
          out.push(...renderField(a, ancestors, depth + 1, inner));
      }
      if (showFields) {
        if (args.length) out.push(`${inner}**Fields**`, "");
        const next = new Set(ancestors).add(named);
        for (const f of typeFields)
          out.push(...renderField(f, next, depth + 1, inner));
      }
      out.push("", `${pad}  </Expandable>`);
    }
    out.push(`${pad}</ResponseField>`, "");
    return out;
  }

  // ----- Page renderers (each returns a full MDX document) -----
  // Everything within a category is listed alphabetically by name.
  const byName = (a, b) => a.name.localeCompare(b.name);
  const catQueries = (catId) =>
    queries.filter((q) => q.category === catId).sort(byName);
  const catMutations = (catId) =>
    mutations.filter((m) => m.category === catId).sort(byName);
  const catTypes = (catId) =>
    types
      .filter((t) => t.category === catId && !isBoilerplate(t.name))
      .sort(byName);

  function renderOverview(cat) {
    // The category description is the frontmatter subtitle; don't repeat it here.
    const lines = frontmatter(cat.label, cat.description);
    const cQueries = catQueries(cat.id);
    const cMutations = catMutations(cat.id);
    const listOp = (op) =>
      `- [\`${op.name}\`](${opUrl(op)})${lifecycleBadge(
        op.lifecycle
      )} — ${escapeCell(op.description)}`;

    if (cQueries.length) {
      lines.push("## Queries", "");
      cQueries.forEach((op) => lines.push(listOp(op)));
      lines.push("");
    }
    if (cMutations.length) {
      lines.push("## Mutations", "");
      cMutations.forEach((op) => lines.push(listOp(op)));
      lines.push("");
    }

    const inCat = catTypes(cat.id);
    for (const [heading, kind] of KIND_ORDER) {
      const group = inCat.filter((t) => t.kind === kind && !isResultObject(t));
      if (!group.length) continue;
      lines.push(`## ${heading}`, "");
      for (const t of group)
        lines.push(
          `- [${t.name}](${typeUrl(t.name)})${lifecycleBadge(
            t.lifecycle
          )} — ${escapeCell(t.description)}`
        );
      lines.push("");
    }
    return lines.join("\n");
  }

  function renderOperationPage(op) {
    // op.description is the frontmatter subtitle; go straight to the details.
    const lines = frontmatter(op.name, op.description);
    lines.push(`**Required scopes:** ${scopeList(op.scopes)}`, "");

    if (op.args && op.args.length) {
      lines.push("## Arguments", "");
      for (const arg of op.args)
        lines.push(...renderField(arg, new Set(), 1, ""));
    }

    // The response is itself a field: the name you select (the operation name),
    // typed by the return type, carrying the return type's description and — via
    // Show fields — that type's fields.
    lines.push("## Returns", "");
    const retNamed = op.returnType.ofType;
    const retType = retNamed ? typeByName[retNamed] : null;
    lines.push(
      ...renderField(
        {
          name: op.name,
          type: op.returnType,
          description: retType ? retType.description : null,
          args: [],
        },
        new Set(),
        0,
        ""
      )
    );
    // Interface/union returns can resolve to more than one concrete type.
    if (retType && retType.kind === "INTERFACE") {
      const impls = implementorsOf(retNamed);
      if (impls.length)
        lines.push(
          `**Possible types:** ${impls
            .map((t) => `[\`${t.name}\`](${typeUrl(t.name)})`)
            .join(", ")}`,
          ""
        );
    }

    lines.push("## Example", "");
    lines.push(exampleOperation(op), "");
    return lines.join("\n");
  }

  function renderTypePage(type) {
    // type.description is the frontmatter subtitle; don't repeat it in the body.
    const lines = frontmatter(type.name, type.description);

    if (type.kind === "INTERFACE") {
      const impls = implementorsOf(type.name);
      if (impls.length)
        lines.push(
          `**Implemented by:** ${impls
            .map((t) => `[\`${t.name}\`](${typeUrl(t.name)})`)
            .join(", ")}`,
          ""
        );
    }
    // Fields render as the same ResponseField explorer as operations: each
    // field opens to reveal its own fields when its type is an object. Seed the
    // cycle guard with this type so a self-referential field doesn't re-expand.
    const fieldList = (fields) => {
      for (const f of fields)
        lines.push(...renderField(f, new Set([type.name]), 1, ""));
    };
    if (type.kind === "OBJECT" || type.kind === "INTERFACE") {
      const wh = webhooksLine(type);
      if (wh) lines.push(wh, "");
      if (type.scopes && type.scopes.length)
        lines.push(`**Required scopes:** ${scopeList(type.scopes)}`, "");
      if (type.fields && type.fields.length) fieldList(type.fields);
    } else if (type.kind === "INPUT_OBJECT") {
      if (type.inputFields && type.inputFields.length)
        fieldList(type.inputFields);
    } else if (type.kind === "ENUM") {
      lines.push(enumTable(type), "");
    }
    return lines.join("\n");
  }

  function renderScopesPage() {
    const lines = frontmatter(
      "Access scopes",
      "Scopes that API tokens carry and the fields they gate"
    );
    lines.push(
      "Every API token carries a set of **scopes**. A field is denied unless your",
      "token holds every scope listed on it — and because a nested field's scope is",
      "additive to its parent's, a request needs the **union** of the scopes along",
      "each selection path it touches. Scopes marked **Used in v3** apply to fields",
      "in this API version; the rest belong to other parts of the Redo platform.",
      ""
    );
    const sorted = [...scopes].sort((a, b) => a.scope.localeCompare(b.scope));
    for (const s of sorted) {
      lines.push(`<a id="scope-${s.scope}" />`);
      lines.push(`### \`${s.scope}\``, "");
      const used = referencedScopes.has(s.scope) ? "Yes" : "No";
      lines.push(
        `**Resource:** ${s.resourceLabel} · **Access:** ${s.access} · **Used in v3:** ${used}`,
        ""
      );
      if (s.description) lines.push(mdxText(s.description), "");
    }
    return lines.join("\n");
  }

  // ----- Write pages -----
  const format = (src) =>
    prettier.format(src, { parser: "mdx", proseWrap: "always" });
  const write = (rel, src) => {
    const file = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, format(src));
  };

  fs.rmSync(outDir, { recursive: true, force: true });
  let count = 0;
  for (const cat of categories) {
    write(`${cat.id}/overview.mdx`, renderOverview(cat));
    count++;
    for (const op of catQueries(cat.id)) {
      write(`${cat.id}/queries/${slug(op.name)}.mdx`, renderOperationPage(op));
      count++;
    }
    for (const op of catMutations(cat.id)) {
      write(
        `${cat.id}/mutations/${slug(op.name)}.mdx`,
        renderOperationPage(op)
      );
      count++;
    }
    for (const t of catTypes(cat.id)) {
      write(`${cat.id}/${slug(t.name)}.mdx`, renderTypePage(t));
      count++;
    }
  }
  write(`${SCOPES_SLUG}.mdx`, renderScopesPage());
  count++;

  // ----- Build the v3 nav and patch docs.json -----
  const navGroups = categories.map((cat) => {
    const pages = [];
    const cQueries = catQueries(cat.id);
    const cMutations = catMutations(cat.id);
    if (cQueries.length)
      pages.push({ group: "Queries", pages: cQueries.map((op) => opUrl(op)) });
    if (cMutations.length)
      pages.push({
        group: "Mutations",
        pages: cMutations.map((op) => opUrl(op)),
      });
    // Nav "Objects" section: object/interface types only. Input objects, result
    // payloads, enums, and scalars still get pages (linked from operations and
    // listed on the overview) but no sidebar entry.
    const objects = catTypes(cat.id).filter(
      (t) =>
        (t.kind === "OBJECT" || t.kind === "INTERFACE") && !isResultObject(t)
    );
    if (objects.length)
      pages.push({
        group: "Objects",
        pages: objects.map((t) => typeUrl(t.name)),
      });
    return { group: cat.label, root: overviewUrl(cat.id), pages };
  });
  navGroups.push({ group: "Access", pages: [SCOPES_PAGE] });

  if (docsJsonPath) patchDocsJson(docsJsonPath, navGroups);

  console.error(`  Generated ${count} v3 reference pages into ${outDir}`);
  if (docsJsonPath)
    console.error(`  Patched v3 reference nav in ${docsJsonPath}`);
  if (emptyCategories.length)
    console.error(
      `  Skipped ${emptyCategories.length} empty categor${
        emptyCategories.length === 1 ? "y" : "ies"
      } (no members yet): ${emptyCategories.join(", ")}`
    );
}

// Replace the v3 version's generated groups in docs.json, preserving the
// hand-authored "Getting Started" group. Keeps the file prettier-clean.
function patchDocsJson(docsJsonPath, navGroups) {
  const docs = JSON.parse(fs.readFileSync(docsJsonPath, "utf8"));
  const tab = (docs.navigation.tabs || []).find(
    (t) => t.tab === "API Reference"
  );
  const version = tab && (tab.versions || []).find((v) => /v3/.test(v.version));
  if (!version) {
    console.error(
      "  WARNING: could not find the v3 version in docs.json — nav not patched."
    );
    return;
  }
  const gettingStarted = (version.groups || []).find(
    (g) => g.group === "Getting Started"
  );
  version.groups = [...(gettingStarted ? [gettingStarted] : []), ...navGroups];
  const formatted = prettier.format(JSON.stringify(docs, null, 2), {
    parser: "json",
  });
  fs.writeFileSync(docsJsonPath, formatted);
}

main();
