# $schema: https://json-schema.org/draft/2020-12/schema#
properties:
  externalId:
    title: External ID
    type: string
  name:
    title: Title
    type: string
  sku:
    title: SKU
    type: string
  weight:
    title: Weight
    $ref: ./weight.schema.yaml
required: [name]
title: Product variant
type: object
