load("@better_rules_javascript//nodejs:rules.bzl", "nodejs_binary")
load("@rules_shell_extra//shell:rules.bzl", "sh_binary")

package(default_visibility = ["//visibility:public"])

sh_binary(
    name = "gen",
    data = ["//redo/api-schema:openapi"],
    main = "gen.sh",
)

sh_test(
    name = "validate_test",
    srcs = ["validate.sh"],
    data = ["//redo/api-schema:openapi"],
    tags = ["local"],
)

nodejs_binary(
    name = "openapi_typescript",
    dep = "@redotech_redodev_npm//openapi-typescript:lib",
    main = "bin/cli.js",
)
