name: Cleanup
description: Save cache and upload profiles
inputs:
  bazel-cache-key:
    required: true
  cache-write:
    default: "true"
runs:
  steps:
    - name: Upload profiles
      uses: actions/upload-artifact@v3
      with:
        name: profile
        path: .profile/
    - name: Shutdown Bazel
      if: inputs.cache-write == 'true'
      run: bazel shutdown
      shell: bash
    - name: Save Bazel cache
      if: inputs.cache-write == 'true'
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/bazel
        key: ${{ inputs.bazel-cache-key }}/${{ github.sha }}
  using: composite
